spring:
    config:
        activate:
            on-profile: prod
    data:
        redis:
            port: 6379
            host: ENC(6lp8JSf2oRVPLNsATCSDPbq+8bf2JR+uV/lm/WF9FHLWUvl46LT+aXP4xENDUDu67bQiIu3hI0ZtfthgeCG9UA==)
decorator:
    datasource:
        p6spy:
            enable-logging: on
server:
    port: 80
    tomcat:
        basedir: ./web
        accesslog:
            enabled: true
            directory: ./logs
            prefix: access_log
            suffix: .log
            pattern: '%h %l %u [%{yy-MM-dd HH:mm:ss}t] "%r" %s %b %D %{User-Agent}i'